### ISSUE TITLE
End-to-end command -> add ability to support custom commits of drivers

### ISSUE THREAD

**Issue by lwsanty** [bblfsh/performance#2]
Currently `e2e` works only with `bblfshd` docker tags which is not enough for development.

The following functionality requested:
1) Pull driver repo at a specific commit.
2) Build Docker image.
3) Run `bblfshd:some-tag` (configurable).
4) Command it to [install the driver from Docker daemon](https://doc.bblf.sh/using-babelfish/advanced-usage.html#adding-drivers-from-the-local-docker-daemon) (docker-daemon:image-name).
5) Test as usual.

**Comment by lwsanty** [comment]
item `2.` concerns me and I think it should be skipped
there're different drivers on different languages and for this case we need to carry all the build environments for all languages in one container with `bblfsh-performance`...

imo `bblfsh-performance` should not perform build during the performance test.
usage cases that I see:
- **CI execution:** here we always gonna deal with driver images that are present in docker hub so no extra builds required
- **debugging by developer** usually developer is able to create an image himself locally, then this image name can be passed to `bblfsh-performance` for an installation to `bblfshd`.

wdyt @dennwc @bzz @kuba-- @creachadair  ?

**Comment by dennwc** [comment]
> we need to carry all the build environments for all languages in one container

This is not true. All you need to build a driver is to have Go 1.12+ locally and have access to Docker. It will re-create the environment there automatically.

> `bblfsh-performance` should not perform build during the performance test

We want to test different branches and we won't ever have images published for those. We need to build it locally, there is no way around it. And it's not as hard as you may think.

**Comment by bzz** [comment]
> there're different drivers on different languages and for this case we need to carry all the build environments for all languages in one container with bblfsh-performance...

Build of language specific parts is hidden inside docker, so there is no need to do that, as @dennwc explain.

It may be ok to skip building in the beginning and make it would only with existing tags, but going further we would definitely want to be able to run it on random revision and that thus we need to plan/keep in mind the ability to build image by calling the docker.
